CREATE DATABASE BAITAPMAU;
GO
USE BAITAPMAU
CREATE TABLE LoaiHang
(
LoaiHangID CHAR(10) PRIMARY KEY,
TenLH NVARCHAR(50) UNIQUE
)
EXEC SP_HELP LoaiHang
EXEC sp_helpconstraint LoaiHang
CREATE TABLE NHACC
(NhaCCID CHAR(10) CONSTRAINT P_NhaCC PRIMARY KEY,
TenNCC NVARCHAR(30) NOT NULL,
diachiNCC NVARCHAR(50),
SdtNCC CHAR(11) NOT NULL)

CREATE TABLE MatHang
(
LoaiHangID CHAR(10) FOREIGN KEY REFERENCES
LOAIHANG(LoaiHangID) ON DELETE CASCADE
ON UPDATE CASCADE,
MathangID CHAR(10) PRIMARY KEY,
TenHang NVARCHAR(50),
Dvtinh NVARCHAR(10),
Slton tinyint DEFAULT 0
)
CREATE TABLE KhachHang
(KhachHangID CHAR(10) PRIMARY KEY,
HotenKH NVARCHAR(30),
DiachiKH NVARCHAR(50),
EmailKH CHAR(30), CHECK(EmailKH LIKE '%@%'),
SdtKH CHAR(11) DEFAULT N'Không có')


CREATE TABLE NhanVien
(NhanVienID CHAR(10) PRIMARY KEY,
HotenNV NVARCHAR(30),
GioitinhNV NVARCHAR(50), CHECK (GIOITINHnv IN ('Nam',N'Nữ')),
NgaysinhNV Date, check(year(NgaysinhNV)<2010),
diachiNV NVARCHAR(50),
EmailNv CHAR(30), CHECK(Emailnv LIKE '%@%'),
SdtNV CHAR(11) DEFAULT N'Không có')


CREATE TABLE Donhangnhap
(DonhangnhapID CHAR(10) PRIMARY KEY,
NhanvienID CHAR(10) REFERENCES Nhanvien(NhanvienID)
ON DELETE CASCADE ON UPDATE CASCADE,
NhaCCID CHAR(10) REFERENCES NhaCC(NhaCCID)
ON DELETE CASCADE ON UPDATE CASCADE,
Ngaynhap Datetime, check (Ngaynhap<=Getdate()),
Trietkhaunhap FLOAT DEFAULT 0)


CREATE TABLE Donhangban
(DonhangbanID CHAR(10) PRIMARY KEY,
NhanvienID CHAR(10) REFERENCES Nhanvien(NhanvienID)
ON DELETE CASCADE ON UPDATE CASCADE,
KhachhangID CHAR(10) REFERENCES Khachhang(KhachhangID)
ON DELETE CASCADE ON UPDATE CASCADE,
Ngayban Datetime ,check (Ngayban<=Getdate()),
Trietkhauban FLOAT DEFAULT 0)


CREATE TABLE ChitietDHN 
(DonhangnhapID CHAR(10) NOT NULL REFERENCES
Donhangnhap(DonhangnhapID) ON DELETE CASCADE,
MathangID CHAR(10) NOT NULL REFERENCES Mathang
(mathangID) ON DELETE CASCADE,
Slnhap TINyint, CHECK(Slnhap>0),
DGnhap FLOAT, CHECK (DGnhap>0),
CONSTRAINT P_CTDHN
PRIMARY KEY(DonhangnhapID,MathangID) )


CREATE TABLE ChitietDHB
(DonhangbanID CHAR(10) NOT NULL REFERENCES
Donhangban(DonhangbanID) ON DELETE CASCADE,
MathangID CHAR(10) NOT NULL REFERENCES 
Mathang(MathangID) ON DELETE CASCADE,
Slban TINyint, CHECK(Slban>0),
DGban FLOAT, CHECK (DGban>0),
CONSTRAINT P_CTDHB
PRIMARY KEY(DonhangbanID,MathangID) )






