CREATE DATABASE BTL_PHAN1
GO
USE BTL_PHAN1
GO
CREATE TABLE DOCGIA
(MADG CHAR(10) CONSTRAINT Pk_DOCGIA PRIMARY KEY,
HOTEN NVARCHAR(30),
NAMSINH INT,
DIACHI NVARCHAR(50))
GO
CREATE TABLE LINHVUC
(MALV CHAR(10) CONSTRAINT Pk_LINHVUC PRIMARY KEY,
TENLV NVARCHAR(30))
GO 
CREATE TABLE SACH
(MASACH CHAR(10) CONSTRAINT Pk_SACH PRIMARY KEY,
MALV CHAR(10) CONSTRAINT Fk_malv_SACH FOREIGN KEY(MALV) REFERENCES LINHVUC(MALV),
TENSACH NVARCHAR(30),
NHAXB NVARCHAR(35),
NAMXB INT,
LANTB INT)
GO
CREATE TABLE PHIEUMUON
(MAPM CHAR(10) CONSTRAINT Pk_PHIEUMUON PRIMARY KEY,
MADG CHAR(10) CONSTRAINT Fk_madg_PHIEUMUON FOREIGN KEY(MADG) REFERENCES DOCGIA(MADG),
MASACH CHAR(10) CONSTRAINT Fk_masach_PHIEUMUON FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
NGAYMUON DATETIME,
NGAYTRA DATETIME,
TINHTRANG NVARCHAR(20))
